siteName: Discuit
siteDescription: A free and open-source community platform.
emailContact:
twitterURL:
discordURL:
githubURL: https://github.com/ronald132
substackURL:

isDevelopment: true
hmacSecret: ronald132@132!
noLogToFile: false
csrfOff: false

addr:
sessionCookieName: SID

# MariaDB configuration:
dbAddr: 127.0.0.1 # Required
dbUser: discuit # Required
dbPassword: discuit # Required
dbName: discuit # Required

# ReCAPTCHA or hCaptcha secret and site-key:
captchaSecret:
captchaSiteKey:
disableRateLimits: false

# TLS certificate key-pair paths:
certFile:
keyFile:

defaultFeedSort: hot
disableForumCreation: false
forumCreationReqPoints: 10
maxForumsPerUser: 20
imagesFolderPath: 'images'
